### ISSUE TITLE
correcciones de products & products detail

### ISSUE THREAD

**Issue by Pudin-con-pasas-uwu** [Pudin-con-pasas-uwu/ecomerce3#8]
- [ ] realizar las categorías y que estén funcionales (Karen)
- [ ] revisar/rediseñar la tarjetas de los productos para que se vean parejos y uniformes (Realpozo)
- [x] que cuando le des click a products te lleve a products details y que muestre los detalles de ese producto en especifico (Arias)

**Comment by lokilaufeysonXD** [comment]
listo los detalles de productos 
![image](https://user-images.githubusercontent.com/55563474/227737023-105d12c2-ab6e-4485-b92d-f2f00bf3b4ea.png)
