### ISSUE TITLE
Correcciones del carrito

### ISSUE THREAD

**Issue by Pudin-con-pasas-uwu** [Pudin-con-pasas-uwu/ecomerce3#9]
- [x] Si no se ha agregado al menos un producto, deberá de aparecer una leyenda que diga: “Carrito vacio. 
- [x] Si hay al menos un producto en el carrito, deberá mostrarse en lista con: imagen, nombre, cantidad y precio.
- [ ] Si hay al menos un producto en el carrito, deberá mostrar un formulario con al menos: nombre, teléfono, correo, estado, dirección, comentarios y botón de realizar pedido (puedes usar el formulario que esta en checkout, ese ya esta hasta medio configurado para que envie la informacion con la que se rellena el formulario al correo que introduzca el cliente)

**Comment by lokilaufeysonXD** [comment]
lo unico que falta es el segundo punto 
![image](https://user-images.githubusercontent.com/55563474/232110128-e9e792c2-36da-40cf-9b49-7c141caa7015.png)
